package de.uzl.itcr.mimic4fhir.table;

public enum MimicFhirTable {
	CONDITION,
	ENCOUNTER,
	ENCOUNTER_ICU,
	LOCATION,
	MEDICATION,
	MEDICATION_ADMINISTRATION,
	MEDICATION_ADMINISTRATION_ICU,
	MEDICATION_DISPENSE,
	MEDICATION_REQUEST,
	OBSERVATION_CHARTEVENTS,
	OBSERVATION_DATETIMEEVENTS,
	OBSERVATION_LABEVENTS,
	OBSERVATION_MICRO_ORG,
	OBSERVATION_MICRO_SUSC,
	OBSERVATION_MICRO_TEST,
	OBSERVATION_OUTPUTEVENTS,
	ORGANIZATION,
	PATIENT,
	PROCEDURE,
	PROCEDURE_ICU,
	SPECIMEN,
	SPECIMEN_LAB
}
